# Mandatory settings

blog_theme: light # Or use dark
name: Chalk
paginate: 25
url: # add your site url (format: https://example.com)


# Optional settings

about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
baseurl: # Set if blog doesn't sit at the root of the domain (format: /blog)
discus_identifier: # Add your Disqus identifier
ga_analytics: # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
scrollappear_enabled: true # Change to false to disable
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: # Add your GitHub handle
  linkedin: # Add your LinkedIn handle
  twitter: # Add your Twitter handle
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address
  ethereum: # Add your Ethereum link or address
  gitlab: # Add your GitLab handle
  youtube: # Add your Youtube handle
  twitch: # Add your Twitch handle
  discord: # Add you Discord server invitation ID
  tumblr: # Add your Tumblr handle
  bitbucket: # Add your Bitbucket handle
  docker: # Add your Docker Hub handle
  instagram: # Add your Instagram handle
  keybase: # Add your Keybase handle
  medium: # Add your Medium handle
  spotify: # Add your Spotify handle
  stackoverflow: # Add your Stack Overflow ID number
  steam: # Add your Steam handle


# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
